services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./:/var/www
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" 
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
